# Site settings
title: Smooth Bear
description: 'Business Card Page'
url: 'https://github.com/smoothbear'
baseurl: 'https://github.com/smoothbear'
profilepic: '/images/smoothbear.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Kim Jung Bin'
  email: kjbin0420@naver.com
  facebook_username: 100011584660621
  github_username:  smoothbear
  linkedin_username:
  meetup_name:

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
